import { Quiz, Medal, MistakeItem } from '../types/quiz';
import { UserProfile } from '../types/auth';

export const initialUser: UserProfile = {
  uid: 'user_marty_001',
  email: 'marty.goboy@edu.com',
  displayName: 'Marty Goboy',
  isGuest: false,
  streak: 0,
  quizzesTaken: 0,
  avgScore: 0,
  totalXP: 0,
  tier: 'Novice Scholar',
  createdAt: new Date().toISOString(),
};

export const sampleQuizzes: Quiz[] = [
  {
    id: 'quiz_cell_biology',
    title: 'Cell Biology: Structure & Function',
    description: 'Comprehensive review of organelles, transport mechanisms, and cellular respiration.',
    category: 'Biology',
    difficulty: 'medium',
    questionTypes: ['multiple_choice', 'true_false'],
    questionsCount: 4,
    createdAt: new Date().toISOString(),
    bestScore: undefined,
    timesTaken: 0,
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        prompt: 'Which organelle is known as the powerhouse of the cell?',
        options: ['Mitochondria', 'Ribosome', 'Golgi apparatus', 'Nucleus'],
        correctAnswer: 0,
        explanation: 'Mitochondria generate ATP through cellular respiration, powering nearly everything the cell does.',
        category: 'Cell Biology',
      },
      {
        id: 'q2',
        type: 'multiple_choice',
        prompt: 'What cellular structure is responsible for protein synthesis?',
        options: ['Lysosome', 'Ribosome', 'Endoplasmic Reticulum', 'Centriole'],
        correctAnswer: 1,
        explanation: 'Ribosomes translate mRNA into polypeptide chains during protein synthesis.',
        category: 'Cell Biology',
      },
      {
        id: 'q3',
        type: 'true_false',
        prompt: 'The cell membrane is entirely impermeable to all solutes.',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'The cell membrane is selectively permeable, allowing certain nonpolar molecules to diffuse freely while regulating ions and polar molecules through protein channels.',
        category: 'Cell Biology',
      },
      {
        id: 'q4',
        type: 'multiple_choice',
        prompt: 'Which organelle packages and sorts proteins for secretion?',
        options: ['Vacuole', 'Peroxisome', 'Golgi apparatus', 'Chloroplast'],
        correctAnswer: 2,
        explanation: 'The Golgi apparatus modifies, sorts, and packages proteins received from the rough ER into vesicles.',
        category: 'Cell Biology',
      },
    ],
  },
  {
    id: 'quiz_genetics',
    title: 'Molecular Genetics & DNA Replication',
    description: 'Key concepts in DNA polymerase, transcription, and translation.',
    category: 'Genetics',
    difficulty: 'hard',
    questionTypes: ['multiple_choice', 'true_false'],
    questionsCount: 3,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    bestScore: undefined,
    timesTaken: 0,
    questions: [
      {
        id: 'g1',
        type: 'multiple_choice',
        prompt: 'Which enzyme synthesizes DNA molecules from deoxyribonucleotides?',
        options: ['DNA Polymerase', 'RNA Helicase', 'Ligase', 'Topoisomerase'],
        correctAnswer: 0,
        explanation: 'DNA Polymerase synthesizes new DNA strands in the 5 to 3 direction.',
        category: 'Molecular Genetics',
      },
      {
        id: 'g2',
        type: 'true_false',
        prompt: 'Adenine pairs with Cytosine in standard Watson-Crick base pairing.',
        options: ['True', 'False'],
        correctAnswer: 1,
        explanation: 'Adenine pairs with Thymine (in DNA) or Uracil (in RNA) via two hydrogen bonds.',
        category: 'Molecular Genetics',
      },
      {
        id: 'g3',
        type: 'multiple_choice',
        prompt: 'What is the role of tRNA in translation?',
        options: ['Transfers amino acids to the ribosome', 'Stores genetic code', 'Splices introns', 'Initiates transcription'],
        correctAnswer: 0,
        explanation: 'Transfer RNA matches codons on mRNA with corresponding amino acids.',
        category: 'Molecular Genetics',
      }
    ],
  },
  {
    id: 'quiz_neuro',
    title: 'Neurobiology & Synaptic Transmission',
    description: 'Action potentials, neurotransmitters, and membrane potentials.',
    category: 'Physiology',
    difficulty: 'medium',
    questionTypes: ['multiple_choice', 'true_false'],
    questionsCount: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    bestScore: undefined,
    timesTaken: 0,
    questions: [
      {
        id: 'n1',
        type: 'multiple_choice',
        prompt: 'Which ion influx triggers neurotransmitter vesicle exocytosis at the axon terminal?',
        options: ['Calcium (Ca2+)', 'Sodium (Na+)', 'Potassium (K+)', 'Chloride (Cl-)'],
        correctAnswer: 0,
        explanation: 'Voltage-gated calcium channels open upon depolarization, causing Ca2+ influx that drives vesicle fusion.',
        category: 'Neurobiology',
      },
      {
        id: 'n2',
        type: 'true_false',
        prompt: 'The resting membrane potential of a neuron is typically around -70 mV.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'Neuronal resting membrane potential is stabilized near -70 mV largely by potassium leak channels and the Na+/K+ ATPase pump.',
        category: 'Neurobiology',
      },
      {
        id: 'n3',
        type: 'multiple_choice',
        prompt: 'What insulation accelerates action potential propagation via saltatory conduction?',
        options: ['Myelin Sheath', 'Astrocyte Foot', 'Microglia', 'Ependymal Layer'],
        correctAnswer: 0,
        explanation: 'The myelin sheath allows the action potential to leap between nodes of Ranvier.',
        category: 'Neurobiology',
      }
    ],
  },
];

export const sampleMedals: Medal[] = [
  {
    id: 'm1',
    title: 'Gold Scholar',
    subtitle: 'High Academic Performance',
    description: 'Maintained an average score above 85% across 20+ completed quizzes.',
    category: 'Excellence',
    unlocked: true,
    unlockedDate: 'Oct 14, 2026',
    progress: 20,
    totalRequired: 20,
    iconUri: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/UjqMgCp8GJ/999ca9h1_expires_30_days.png',
  },
  {
    id: 'm2',
    title: 'Speed Demon',
    subtitle: 'Lightning Answers',
    description: 'Complete a 10-question quiz in under 2 minutes with 90%+ accuracy.',
    category: 'Speed',
    unlocked: true,
    unlockedDate: 'Oct 18, 2026',
    progress: 10,
    totalRequired: 10,
    iconUri: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/UjqMgCp8GJ/t9rvvowe_expires_30_days.png',
  },
  {
    id: 'm3',
    title: 'Curious Mind',
    subtitle: 'Doc Converter',
    description: 'Generate 10 quizzes from customized documents and study materials.',
    category: 'Creation',
    unlocked: false,
    progress: 7,
    totalRequired: 10,
    iconUri: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/UjqMgCp8GJ/w6es531i_expires_30_days.png',
  },
  {
    id: 'm4',
    title: 'Consistency Titan',
    subtitle: '14-Day Streak',
    description: 'Complete at least one quiz every day for 14 consecutive days.',
    category: 'Dedication',
    unlocked: false,
    progress: 6,
    totalRequired: 14,
    iconUri: 'https://storage.googleapis.com/tagjs-prod.appspot.com/v1/UjqMgCp8GJ/cnph2qnt_expires_30_days.png',
  },
];

export const sampleMistakes: MistakeItem[] = [
  {
    id: 'mis_1',
    quizId: 'quiz_cell_biology',
    question: {
      id: 'q_mis_1',
      type: 'multiple_choice',
      prompt: 'Which lipid constitutes the main hydrophobic bilayer of plasma membranes?',
      options: ['Phospholipids', 'Triglycerides', 'Steroids', 'Waxes'],
      correctAnswer: 0,
      explanation: 'Phospholipids have amphipathic properties with hydrophilic phosphate heads and hydrophobic fatty acid tails forming the bilayer.',
      category: 'Cell Membrane',
    },
    userAnswer: 1,
    correctAnswer: 0,
    dateAdded: 'Yesterday',
    mastered: false,
  },
  {
    id: 'mis_2',
    quizId: 'quiz_genetics',
    question: {
      id: 'q_mis_2',
      type: 'multiple_choice',
      prompt: 'During transcription, which RNA polymerase synthesizes pre-mRNA in eukaryotes?',
      options: ['RNA Polymerase I', 'RNA Polymerase II', 'RNA Polymerase III', 'Primase'],
      correctAnswer: 1,
      explanation: 'RNA Polymerase II is the primary enzyme responsible for synthesizing mRNA and most snRNA.',
      category: 'Transcription',
    },
    userAnswer: 0,
    correctAnswer: 1,
    dateAdded: '2 days ago',
    mastered: false,
  },
];
